"""Generate exhaustive Cost and Charges summary for all brokers.

This script:
1. Loads all extracted PDF texts
2. Uses a specified LLM to generate detailed cost and charges analysis
3. Produces a comprehensive markdown report with tables and comparisons
4. Saves structured JSON data for each broker
"""
from __future__ import annotations

import argparse
import json
import sys
import os
from pathlib import Path
import logging
from typing import Optional
from datetime import datetime
import re
import hashlib
import time

PROJECT_ROOT = Path(__file__).resolve().parents[1]
SRC_PATH = PROJECT_ROOT / "src"
if str(SRC_PATH) not in sys.path:
    sys.path.insert(0, str(SRC_PATH))

from be_invest.config_loader import load_brokers_from_yaml
from be_invest.models import Broker

DEFAULT_DATA_DIR = Path("data")
DEFAULT_BROKERS_PATH = DEFAULT_DATA_DIR / "brokers.yaml"
DEFAULT_PDF_TEXT_DIR = DEFAULT_DATA_DIR / "output" / "pdf_text"
DEFAULT_OUTPUT_DIR = DEFAULT_DATA_DIR / "output"
DEFAULT_SUMMARY_FILE = DEFAULT_OUTPUT_DIR / "exhaustive_cost_charges_summary.md"

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(levelname)s - %(message)s"
)
logger = logging.getLogger(__name__)


def get_text_filename_for_broker_source(broker_name: str, ds_description: str, url: str) -> str:
    """Recreate the exact filename generated by the /refresh-pdfs endpoint."""
    safe_broker_name = re.sub(r'[\s/]+', '_', broker_name)
    safe_desc = re.sub(r'[\s/]+', '_', ds_description or 'document')
    url_hash = hashlib.md5(url.encode()).hexdigest()[:8]
    return f"{safe_broker_name}_{safe_desc}_{url_hash}.txt"


def load_pdf_texts_for_brokers(brokers: list[Broker], text_dir: Path) -> dict[str, list]:
    """Load all extracted PDF text files for the given brokers."""
    texts = {}
    if not text_dir.exists():
        logger.warning(f"PDF text directory not found: {text_dir}")
        return texts

    for broker in brokers:
        if not broker.data_sources:
            continue
        
        broker_texts = []
        for ds in broker.data_sources:
            if not ds.url:
                continue

            expected_filename = get_text_filename_for_broker_source(broker.name, ds.description, ds.url)
            text_file_path = text_dir / expected_filename

            if text_file_path.exists():
                try:
                    content = text_file_path.read_text(encoding="utf-8")
                    if content.strip():
                        broker_texts.append({
                            "filename": text_file_path.name,
                            "content": content,
                            "size": len(content)
                        })
                        logger.info(f"📄 Loaded: {text_file_path.name} ({len(content):,} chars) → {broker.name}")
                    else:
                        logger.warning(f"Skipping empty text file for {broker.name}: {text_file_path.name}")
                except Exception as e:
                    logger.error(f"Failed to read text file {text_file_path.name}: {e}")
            else:
                logger.warning(f"Text file not found for {broker.name} source: {ds.url} (expected {expected_filename})")
        
        if broker_texts:
            texts[broker.name] = broker_texts

    return texts


def analyze_broker_costs_with_llm(broker_name: str, texts: list[dict], api_key: str, model: str = "claude-sonnet-4-20250514") -> dict:
    """Analyze broker costs using a specified LLM (OpenAI or Anthropic)."""
    if not texts:
        return {"error": "No text data provided"}

    combined_text = "\n\n".join(t["content"] for t in texts)
    logger.info(f"🔍 Analyzing {broker_name} ({len(combined_text):,} chars) using {model}...")
    
    analysis_prompt = f"""Extract ALL broker fees from the following tariffs for {broker_name}.
Return ONLY a valid JSON object.

{combined_text[:15000]}
"""

    system_prompt = "You are a financial analyst. Return ONLY valid JSON, no explanations or apologies."

    try:
        start_time = time.time()

        # Detect provider from model name
        if model.startswith("claude"):
            # Use Anthropic API
            try:
                import anthropic
            except ImportError:
                logger.error("❌ Anthropic SDK not installed")
                return {"error": "Anthropic not installed"}

            anthropic_key = os.getenv("ANTHROPIC_API_KEY")
            if not anthropic_key:
                logger.error("❌ ANTHROPIC_API_KEY not set")
                return {"error": "ANTHROPIC_API_KEY not set"}

            client = anthropic.Anthropic(api_key=anthropic_key)

            # Add JSON instruction for Claude
            enhanced_prompt = analysis_prompt + "\n\nIMPORTANT: Return ONLY valid JSON. No markdown, no explanations."

            response = client.messages.create(
                model=model,
                max_tokens=4096,
                temperature=0.1,
                system=system_prompt,
                messages=[{"role": "user", "content": enhanced_prompt}]
            )

            response_text = response.content[0].text

            # Clean markdown if present
            if response_text.strip().startswith("```"):
                lines = response_text.strip().split("\n")
                if lines[0].startswith("```"):
                    lines = lines[1:]
                if lines and lines[-1].startswith("```"):
                    lines = lines[:-1]
                response_text = "\n".join(lines).strip()

        else:
            # Use OpenAI API
            try:
                from openai import OpenAI
            except ImportError:
                logger.error("❌ OpenAI SDK not installed")
                return {"error": "OpenAI not installed"}

            openai_key = api_key or os.getenv("OPENAI_API_KEY")
            if not openai_key:
                logger.error("❌ OPENAI_API_KEY not set")
                return {"error": "OPENAI_API_KEY not set"}

            client = OpenAI(api_key=openai_key)

            response = client.chat.completions.create(
                model=model,
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": analysis_prompt}
                ],
                temperature=0.1,
                max_tokens=4000,
                response_format={"type": "json_object"},
            )

            response_text = response.choices[0].message.content.strip() if response.choices else ""

        end_time = time.time()
        logger.info(f"LLM call for {broker_name} completed in {end_time - start_time:.2f} seconds.")

        if not response_text or not response_text.startswith('{'):
            logger.error(f"❌ Invalid or empty response from LLM for {broker_name}. Response: '{response_text[:100]}...'")
            return {"error": "Invalid or empty response from LLM"}

        analysis = json.loads(response_text)
        logger.info(f"✅ Analysis complete for {broker_name}")
        return analysis

    except Exception as e:
        logger.error(f"❌ Analysis failed for {broker_name}: {e}", exc_info=True)
        return {"error": str(e)}


def generate_comprehensive_summary(brokers: list[Broker], pdf_texts: dict[str, list], api_key: str, model: str = "claude-sonnet-4-20250514") -> tuple[str, dict]:
    """Generate comprehensive summary for all brokers."""
    all_analyses = {}

    logger.info("\n" + "="*80)
    logger.info("📊 ANALYZING BROKER COSTS & CHARGES")
    logger.info("="*80)

    for broker in brokers:
        if broker.name in pdf_texts:
            analysis = analyze_broker_costs_with_llm(
                broker.name, pdf_texts[broker.name], api_key, model
            )
            all_analyses[broker.name] = analysis
        else:
            logger.warning(f"⚠️ No PDF text found for {broker.name}, it will be excluded from the analysis.")
            all_analyses[broker.name] = {"error": "No text data"}
    
    logger.info("\n" + "="*80)
    logger.info("📝 GENERATING COMPREHENSIVE SUMMARY")
    logger.info("="*80)

    # This part is now simplified as the detailed summary generation is very complex and brittle.
    # We will just save the JSON data. A separate process could create the markdown.
    
    summary = "# Broker Cost Analysis Summary\n\n"
    brokers_included = [b for b in all_analyses.keys() if "error" not in all_analyses[b]]
    summary += f"Analysis complete for the following brokers: {', '.join(brokers_included)}\n\n"
    summary += "Detailed JSON data has been saved to `data/output/broker_cost_analyses.json`."
    
    logger.info("✅ Comprehensive summary generation skipped in favor of stable JSON output.")
    return summary, all_analyses


def main():
    parser = argparse.ArgumentParser(description="Generate exhaustive Cost and Charges summary for all brokers.")
    parser.add_argument("--brokers", type=Path, default=DEFAULT_BROKERS_PATH)
    parser.add_argument("--pdf-text-dir", type=Path, default=DEFAULT_PDF_TEXT_DIR)
    parser.add_argument("--output", type=Path, default=DEFAULT_SUMMARY_FILE)
    parser.add_argument("--model", type=str, default="claude-sonnet-4-20250514", help="LLM model to use (default: claude-sonnet-4-20250514). For OpenAI use: gpt-4o")
    parser.add_argument("--api-key-env", type=str, default="OPENAI_API_KEY")
    parser.add_argument("--log-level", choices=["DEBUG", "INFO", "WARNING", "ERROR"], default="INFO")
    parser.add_argument("--json-only", action="store_true")
    args = parser.parse_args()
    
    logging.getLogger().setLevel(getattr(logging, args.log_level, "INFO"))

    logger.info("="*80)
    logger.info("🚀 EXHAUSTIVE COST & CHARGES SUMMARY GENERATOR")
    logger.info("="*80)

    logger.info("\n📂 Loading broker configurations...")
    brokers = load_brokers_from_yaml(args.brokers)
    logger.info(f"Found {len(brokers)} brokers.")

    logger.info("\n📂 Loading extracted PDF texts...")
    pdf_texts = load_pdf_texts_for_brokers(brokers, args.pdf_text_dir)
    if not pdf_texts:
        logger.error("❌ No PDF texts found. Run the /refresh-pdfs endpoint first.")
        return 1
    logger.info(f"✅ Loaded texts for {len(pdf_texts)} broker(s).")

    api_key = os.getenv(args.api_key_env)
    if not api_key:
        logger.error(f"❌ {args.api_key_env} environment variable not set.")
        return 1

    summary, analyses = generate_comprehensive_summary(
        brokers, pdf_texts, api_key, args.model
    )

    json_output_path = args.output.parent / "broker_cost_analyses.json"
    logger.info(f"\n💾 Saving JSON analyses to: {json_output_path}")
    json_output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(json_output_path, "w", encoding="utf-8") as f:
        json.dump(analyses, f, indent=2, ensure_ascii=False)
    logger.info("✅ JSON analyses saved.")

    if summary and not args.json_only:
        logger.info(f"\n💾 Saving markdown summary to: {args.output}")
        args.output.write_text(summary, encoding="utf-8")
        logger.info("✅ Summary saved.")

    logger.info("\n" + "="*80)
    logger.info("✅ COMPLETE")
    logger.info("="*80)

    return 0


if __name__ == "__main__":
    sys.exit(main())
