"""
Setup configuration for be-invest package.
Used by Vercel and other deployment platforms to install the package.
"""
from setuptools import setup, find_packages
from pathlib import Path

# Read README for long description
readme_file = Path(__file__).parent / "README.md"
long_description = readme_file.read_text(encoding="utf-8") if readme_file.exists() else ""

setup(
    name="be-invest",
    version="0.1.0",
    description="Toolkit for aggregating Belgian broker fee data",
    long_description=long_description,
    long_description_content_type="text/markdown",
    author="AutoGenerated",
    python_requires=">=3.9",
    packages=find_packages(where="src"),
    package_dir={"": "src"},
    install_requires=[
        "PyYAML>=6.0",
        "pydantic>=2.0",
        "requests>=2.31",
        "pdfminer.six>=20221105",
        "beautifulsoup4>=4.12.0",
        "lxml>=4.9.0",
        "playwright>=1.45",
        "openai>=1.13.3",
        "anthropic>=0.40.0",
        "fastapi>=0.110",
        "uvicorn[standard]>=0.29",
        "python-multipart>=0.0.9",
        "feedparser>=6.0.10",
    ],
    extras_require={
        "dev": [
            "pytest>=7.0",
            "black>=23.0",
            "flake8>=6.0",
        ],
    },
    entry_points={
        "console_scripts": [],
    },
)

