"""Debug script to test fetching and text extraction for the ING Self Invest PDF."""
from __future__ import annotations

import sys
from pathlib import Path
import logging
import hashlib
import re

# Add src directory to Python path
PROJECT_ROOT = Path(__file__).resolve().parents[1]
SRC_PATH = PROJECT_ROOT / "src"
if str(SRC_PATH) not in sys.path:
    sys.path.insert(0, str(SRC_PATH))

from be_invest.config_loader import load_brokers_from_yaml
from be_invest.sources.scrape import _fetch_url
from be_invest.api.server import pdf_bytes_to_text  # Import the server's extraction logic

logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s")
logger = logging.getLogger(__name__)

def get_text_filename_for_source(broker_name: str, ds_description: str, url: str) -> str:
    """Recreate the exact filename generated by the /refresh-pdfs endpoint."""
    safe_broker_name = re.sub(r'[\s/]+', '_', broker_name)
    safe_desc = re.sub(r'[\s/]+', '_', ds_description or 'document')
    url_hash = hashlib.md5(url.encode()).hexdigest()[:8]
    return f"{safe_broker_name}_{safe_desc}_{url_hash}.txt"

def main():
    """Finds the ING Self Invest URL, fetches it, and attempts text extraction."""
    brokers_yaml_path = PROJECT_ROOT / "data" / "brokers.yaml"
    if not brokers_yaml_path.exists():
        logger.error("Could not find brokers.yaml at: %s", brokers_yaml_path)
        return

    logger.info("Loading brokers from: %s", brokers_yaml_path)
    brokers = load_brokers_from_yaml(brokers_yaml_path)

    ing_broker = next((b for b in brokers if b.name.lower() == "ing self invest"), None)

    if not ing_broker:
        logger.error("ING Self Invest not found in brokers.yaml.")
        return

    if not ing_broker.data_sources:
        logger.error("ING Self Invest has no data sources defined in brokers.yaml.")
        return

    # Process each data source for ING
    for ds_idx, ds in enumerate(ing_broker.data_sources):
        ing_url = ds.url
        if not ing_url:
            logger.warning("ING Self Invest data source %d has no URL. Skipping.", ds_idx)
            continue

        logger.info("Found ING Self Invest URL (Source %d): %s", ds_idx, ing_url)

        # --- Step 1: Fetch the URL ---
        logger.info("Attempting to fetch the URL...")
        data, error = _fetch_url(ing_url, timeout=20.0)
        if not data:
            logger.error("❌ FAILURE: Fetching the URL returned no data for source %d. Error: %s", ds_idx, error)
            continue
        
        logger.info("✅ SUCCESS: Successfully fetched the ING Self Invest PDF (%d bytes).", len(data))

        # --- Step 2: Attempt Text Extraction ---
        logger.info("Attempting to extract text from the downloaded PDF...")
        try:
            text = pdf_bytes_to_text(data)
            if text and text.strip():
                logger.info("✅ SUCCESS: Successfully extracted text.")
                logger.info("Extracted %d characters.", len(text))
                
                # Recreate the expected filename
                expected_filename = get_text_filename_for_source(ing_broker.name, ds.description, ing_url)
                debug_output_path = PROJECT_ROOT / "data" / "output" / "pdf_text" / expected_filename
                debug_output_path.parent.mkdir(parents=True, exist_ok=True)
                debug_output_path.write_text(text, encoding="utf-8")
                logger.info("Saved extracted text for review to: %s", debug_output_path)

            else:
                logger.error("❌ FAILURE: Text extraction returned empty content for source %d. The PDF might be an image or have other issues.", ds_idx)
        except Exception:
            logger.error("❌ EXCEPTION: An error occurred during text extraction for source %d.", ds_idx, exc_info=True)


if __name__ == "__main__":
    main()
